export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const ADD_BOOTCAMP = "ADD_BOOTCAMP";
export const ADD_COURSE = "ADD_COURSE";
export const ADD_BOOTCAMP_SUCCESS = "ADD_BOOTCAMP_SUCCESS";
export const ADD_BOOTCAMP_FAILED = "ADD_BOOTCAMP_FAILED";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";
export const ADD_COURSE_FAILED = "ADD_COURSE_FAILED";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
